### PR TITLE
docs: update readme

### PR DESCRIPTION
**Pull request by axiangcoding**
- **Description:** update readme and provide a example of how to use wt-profile-tool
- **Issue:** None
- **Dependencies:** None

### CODE REVIEW

**Review by RaidFourms — APPROVED** [review]
Beat me to it 😭

still looks good 👍

**Comment by axiangcoding** [comment]
> Beat me to it 😭
> 
> still looks good 👍

hhh

**Comment by axiangcoding** [comment]
@RaidFourms rest today, all yours now

**Comment by axiangcoding** [comment]
> > @RaidFourms rest today, all yours now
> 
> it's 3 am😭😭

you should rest earlier....Nothing worth  than health

**Pull request merged**
