### PR TITLE
core: support request proxy settings

### PR DESCRIPTION
**Pull request by axiangcoding**
- **Description:** support request proxy settings
- **Issue:** #17 
- **Dependencies:** None

### CODE REVIEW

**Comment by RaidFourms** [comment]
What's the port for?

**Comment by axiangcoding** [comment]
> What's the port for?

what port?

**Comment by RaidFourms** [comment]
> > What's the port for?
> 
> 
> 
> what port?

10809 in test_main

**Comment by axiangcoding** [comment]
You can find the way to write this setting in the [httpx documentation](https://www.python-httpx.org/advanced/#http-proxying).

**Comment by axiangcoding** [comment]
> > > What's the port for?
> > 
> > 
> > what port?
> 
> 10809 in test_main

Just a test case. It has no special meaning.

**Review by RaidFourms — APPROVED** [review]
ah ok

**Pull request merged**
